name: main

on:
  push:
    branches:
      - main
    paths:
      - internal/**/*
      - cmd/**/*
      - test/**/*
      - .github/**.*

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21.3"
      - uses: pre-commit/action@v2.0.0
